#!/usr/bin/env python3
"""L0 DSL 校验：meta/*.yaml 内部一致性 + 与现有 JSON Schema **canonical-equal** 校验。

⚠️ **承诺降级声明（v1 → v2）**：
    Plan v1 原本写"现有 JSON → DSL 反向生成 → 重新编译回 JSON **byte-equal**"，
    实施时降级为 **canonical-equal**（对象树等价）。原因：
    - phase-transitions.json 用了手工对齐空格让 next 列对齐
    - state-schema.json 用了选择性紧凑数组（短数组单行 / 复杂对象多行）
    - 字符级 byte-equal 工作量约 5x，运行时 `json.load` 后行为完全相同
    canonical-equal 已能保证运行时正确性。

Phase 2 引入。三类校验：

A. **DSL 内部一致性**：
   - phases.yaml 的 next/canSkipTo 引用合法（指向已定义的 phase id）
   - state-schema.yaml 的 PhaseId enum 与 phases.yaml 的 id 集合一致
   - commands.yaml 的 file 路径实际存在

B. **DSL → JSON canonical 等价性**：
   - phases.yaml 编译后的 transitions 对象 == phase-transitions.json 解析后的 transitions
   - state-schema.yaml 解析后的对象 == state-schema.json 解析后的对象
   - 不要求字符级 byte-equal，仅要求语义（对象树）等价

C. **现有产物完整性**：
   - phase-transitions.json / state-schema.json 文件存在且可解析

CLI:
    python scripts/validate_meta.py                # 全部 3 组校验
    python scripts/validate_meta.py --scope=internal  # 仅 A
    python scripts/validate_meta.py --scope=equivalence  # 仅 B
    python scripts/validate_meta.py --format=md|json|console

退出码：
    0 PASS / 1 WARN / 2 FAIL / 3 ERROR
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import paths, meta_loader, reporters
from lib.reporters import Severity, Finding, CheckResult, Report


# ----------------------------------------------------------------------------
# DSL → JSON 编译器
# ----------------------------------------------------------------------------

def compile_phases_to_transitions(phases_meta: dict) -> dict:
    """phases.yaml → phase-transitions.json 等价对象。

    输出含 ``$generatedFrom`` / ``$doNotEdit`` sentinel 字段，明示该对象由 DSL 编译产出。
    sentinel 字段不参与 ``_diff_objects`` 等价性比较（见 ``SENTINEL_FIELDS``）。
    """
    phases_list = phases_meta.get("phases", [])
    rules = phases_meta.get("rules", {})

    transitions = {}
    for p in phases_list:
        transitions[p["id"]] = {
            "next": p.get("next"),
            "canSkipTo": p.get("canSkipTo"),
        }

    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$generatedFrom": "meta/phases.yaml",
        "$doNotEdit": "Auto-generated by scripts/render_artifacts.py from meta/phases.yaml. Edit the YAML source then run `python3 scripts/render_artifacts.py --write-json --write`.",
        "title": "PhaseTransitions",
        "description": "合法的阶段流转映射表（唯一权威来源）。编排器在每次更新 currentPhase 前，MUST 查此表确认新阶段是当前阶段的合法后继。",
        "transitions": transitions,
        "rules": {
            "forward": rules.get("forward", ""),
            "skipCondition": rules.get("skipCondition", ""),
            "rollback": rules.get("rollback", ""),
            "termination": rules.get("termination", ""),
        },
    }


def compile_state_schema(state_meta: dict) -> dict:
    """state-schema.yaml → state-schema.json 等价对象。

    剔除以 ``$comment`` 开头的元数据字段（YAML 注释，不属于 JSON Schema），
    并在 ``$schema`` 之后插入 ``$generatedFrom`` / ``$doNotEdit`` sentinel。
    """
    out: dict = {}
    inserted_sentinel = False
    for k, v in state_meta.items():
        if k.startswith("$comment"):
            continue
        out[k] = v
        # 在 $schema 之后立即插入 sentinel
        if k == "$schema" and not inserted_sentinel:
            out["$generatedFrom"] = "meta/state-schema.yaml"
            out["$doNotEdit"] = (
                "Auto-generated by scripts/render_artifacts.py from meta/state-schema.yaml. "
                "Edit the YAML source then run `python3 scripts/render_artifacts.py --write-json --write`."
            )
            inserted_sentinel = True
    # 若没有 $schema 字段（极罕见），把 sentinel 放最前
    if not inserted_sentinel:
        sentinel = {
            "$generatedFrom": "meta/state-schema.yaml",
            "$doNotEdit": "Auto-generated by scripts/render_artifacts.py.",
        }
        out = {**sentinel, **out}
    return out


# Sentinel 字段集（_diff_objects 比较时跳过）
SENTINEL_FIELDS = {"$generatedFrom", "$doNotEdit"}


# ----------------------------------------------------------------------------
# A. DSL 内部一致性
# ----------------------------------------------------------------------------

def check_dsl_internal(meta: dict) -> CheckResult:
    check = CheckResult(
        check_id="dsl-internal",
        description="DSL 内部一致性（meta/ 各文件相互引用合法）",
    )

    phases = meta.get("phases")
    state_schema = meta.get("state_schema")
    commands = meta.get("commands")

    if phases is None:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.WARN,
            title="meta/phases.yaml 不存在",
            fix_hint="运行 python3 scripts/seed_meta_from_existing.py --write",
        ))
        return check

    # A1: phases 内部 — id 唯一
    phase_list = phases.get("phases", [])
    ids = [p.get("id") for p in phase_list]
    seen = set()
    for pid in ids:
        if pid in seen:
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.FAIL,
                title=f"phases.yaml 中 id '{pid}' 重复",
                file=str(paths.to_relative(paths.META_PHASES)),
            ))
        seen.add(pid)

    # A2: phases — next / canSkipTo 引用合法
    id_set = set(ids)
    for p in phase_list:
        for slot in ("next", "canSkipTo"):
            v = p.get(slot)
            if v is None:
                continue
            if v not in id_set:
                check.findings.append(Finding(
                    check_id=check.check_id, severity=Severity.FAIL,
                    title=f"phases.yaml 中 '{p.get('id')}' 的 {slot}='{v}' 不在 id 集合内",
                    file=str(paths.to_relative(paths.META_PHASES)),
                ))

    # A3: state-schema PhaseId enum 与 phases.yaml id 集合一致
    if state_schema is not None:
        defs = state_schema.get("definitions", {})
        phase_id_def = defs.get("PhaseId", {})
        enum_ids = set(phase_id_def.get("enum", []))
        only_phases = id_set - enum_ids
        only_schema = enum_ids - id_set
        for pid in sorted(only_phases):
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.FAIL,
                title=f"phases.yaml 中 '{pid}' 缺失于 state-schema.yaml#definitions.PhaseId.enum",
                file=str(paths.to_relative(paths.META_STATE_SCHEMA)),
            ))
        for pid in sorted(only_schema):
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.FAIL,
                title=f"state-schema.yaml#definitions.PhaseId.enum 中 '{pid}' 缺失于 phases.yaml",
                file=str(paths.to_relative(paths.META_PHASES)),
            ))

    # A4: commands.yaml 的 file 路径实际存在
    if commands is not None:
        for c in commands.get("commands", []):
            file_rel = c.get("file")
            if not file_rel:
                check.findings.append(Finding(
                    check_id=check.check_id, severity=Severity.WARN,
                    title=f"commands.yaml 中 '{c.get('name')}' 缺少 file 字段",
                ))
                continue
            file_abs = paths.CLAUDE_ROOT / file_rel
            if not file_abs.is_file():
                check.findings.append(Finding(
                    check_id=check.check_id, severity=Severity.FAIL,
                    title=f"commands.yaml 中 '{c.get('name')}' 引用的文件不存在：{file_rel}",
                    fix_hint="检查 file 字段或确认命令文件存在于 .claude/commands/",
                ))

    if not check.findings:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.PASS,
            title=f"DSL 内部一致性通过（{len(id_set)} 阶段，"
                  f"{len(commands.get('commands', []) if commands else [])} 命令）",
        ))
    return check


# ----------------------------------------------------------------------------
# B. DSL → JSON 等价性（canonical-equal）
# ----------------------------------------------------------------------------

def check_phases_equivalence(meta: dict) -> CheckResult:
    check = CheckResult(
        check_id="dsl-phases-equiv",
        description="phases.yaml 编译产出 ↔ phase-transitions.json 对象树等价",
    )
    phases = meta.get("phases")
    if phases is None:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.WARN,
            title="phases.yaml 不存在，跳过等价性校验",
        ))
        return check

    if not paths.PHASE_TRANSITIONS.is_file():
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.FAIL,
            title="phase-transitions.json 不存在",
            file=str(paths.to_relative(paths.PHASE_TRANSITIONS)),
        ))
        return check

    compiled = compile_phases_to_transitions(phases)
    actual = json.loads(paths.PHASE_TRANSITIONS.read_text(encoding="utf-8"))

    diffs = _diff_objects(compiled, actual)
    if diffs:
        for path, msg in diffs[:10]:
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.FAIL,
                title=f"对象树差异：{path}",
                message=msg,
                fix_hint="改 phases.yaml 或与 phase-transitions.json 对齐",
            ))
        if len(diffs) > 10:
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.INFO,
                title=f"...省略 {len(diffs) - 10} 处差异",
            ))
    else:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.PASS,
            title="phases.yaml 与 phase-transitions.json 对象树等价",
        ))
    return check


def check_state_schema_equivalence(meta: dict) -> CheckResult:
    check = CheckResult(
        check_id="dsl-state-schema-equiv",
        description="state-schema.yaml ↔ state-schema.json 对象树等价",
    )
    state_meta = meta.get("state_schema")
    if state_meta is None:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.WARN,
            title="state-schema.yaml 不存在，跳过等价性校验",
        ))
        return check

    if not paths.STATE_SCHEMA.is_file():
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.FAIL,
            title="state-schema.json 不存在",
            file=str(paths.to_relative(paths.STATE_SCHEMA)),
        ))
        return check

    compiled = compile_state_schema(state_meta)
    actual = json.loads(paths.STATE_SCHEMA.read_text(encoding="utf-8"))

    diffs = _diff_objects(compiled, actual)
    if diffs:
        for path, msg in diffs[:10]:
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.FAIL,
                title=f"对象树差异：{path}",
                message=msg,
                fix_hint="改 state-schema.yaml 或与 state-schema.json 对齐",
            ))
        if len(diffs) > 10:
            check.findings.append(Finding(
                check_id=check.check_id, severity=Severity.INFO,
                title=f"...省略 {len(diffs) - 10} 处差异",
            ))
    else:
        check.findings.append(Finding(
            check_id=check.check_id, severity=Severity.PASS,
            title="state-schema.yaml 与 state-schema.json 对象树等价",
        ))
    return check


# ----------------------------------------------------------------------------
# Object diff（深度对比，含路径）
# ----------------------------------------------------------------------------

def _diff_objects(a, b, path: str = "$") -> list[tuple[str, str]]:
    """深度对比两个对象。返回 [(path, message)]。

    忽略 ``SENTINEL_FIELDS`` 中的字段（如 ``$generatedFrom`` / ``$doNotEdit``），
    因为它们是元数据声明，与运行时语义无关。
    """
    out: list[tuple[str, str]] = []
    if type(a) != type(b):
        out.append((path, f"类型不同: {type(a).__name__} vs {type(b).__name__}"))
        return out
    if isinstance(a, dict):
        # 剔除 sentinel 字段后再比对
        ka = {k for k in a.keys() if k not in SENTINEL_FIELDS}
        kb = {k for k in b.keys() if k not in SENTINEL_FIELDS}
        only_a = ka - kb
        only_b = kb - ka
        for k in sorted(only_a):
            out.append((f"{path}.{k}", f"DSL 多出键: {k}"))
        for k in sorted(only_b):
            out.append((f"{path}.{k}", f"JSON 多出键: {k}"))
        for k in sorted(ka & kb):
            out.extend(_diff_objects(a[k], b[k], f"{path}.{k}"))
    elif isinstance(a, list):
        if len(a) != len(b):
            out.append((path, f"列表长度不同: {len(a)} vs {len(b)}"))
            return out
        for i, (xa, xb) in enumerate(zip(a, b)):
            out.extend(_diff_objects(xa, xb, f"{path}[{i}]"))
    else:
        if a != b:
            sa = repr(a)[:60]
            sb = repr(b)[:60]
            out.append((path, f"值不同: DSL={sa}  JSON={sb}"))
    return out


# ----------------------------------------------------------------------------
# 入口
# ----------------------------------------------------------------------------

DIMENSIONS = {
    "internal": [check_dsl_internal],
    "equivalence": [check_phases_equivalence, check_state_schema_equivalence],
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="validate_meta",
        description="ai-team meta/ DSL 校验（Phase 2）",
    )
    ap.add_argument("--scope", default="all",
                    choices=["all", "internal", "equivalence"])
    ap.add_argument("--format", default="console", choices=["console", "md", "json"])
    args = ap.parse_args(argv)

    try:
        meta = meta_loader.load_all()
    except Exception as e:
        print(f"加载 meta/*.yaml 失败：{type(e).__name__}: {e}", file=sys.stderr)
        return 3

    report = Report(title="DSL 校验报告（Phase 2）")
    selected: list = []
    if args.scope in ("all", "internal"):
        selected.extend(DIMENSIONS["internal"])
    if args.scope in ("all", "equivalence"):
        selected.extend(DIMENSIONS["equivalence"])

    for fn in selected:
        try:
            report.checks.append(fn(meta))
        except Exception as e:
            c = CheckResult(check_id=fn.__name__, description=f"({fn.__name__})")
            c.findings.append(Finding(
                check_id=fn.__name__, severity=Severity.ERROR,
                title=f"维度执行异常：{type(e).__name__}",
                message=str(e),
            ))
            report.checks.append(c)

    report.summary = {
        "phases_yaml": "loaded" if meta["phases"] else "missing",
        "state_schema_yaml": "loaded" if meta["state_schema"] else "missing",
        "commands_yaml": "loaded" if meta["commands"] else "missing",
        "scope": args.scope,
    }
    return reporters.emit(report, fmt=args.format)


if __name__ == "__main__":
    sys.exit(main())
